/*************************************************************************************************************************************************************************
 * @author     Ramaseshu
 * @date       Jan 04, 2019
 * @decription Defines Constants that are applicable across applications
 *************************************************************************************************************************************************************************/

public class CoreConstants {

    /**
     * @description Enum of decision
     *
     * @return Yes or No
     */
    public enum Decision {Yes, No}

    /**
     * Delimiters
     */
    public static final String DELIMITER_AT = '@';
    public static final String DELIMITER_COLON = ':';
    public static final String DELIMITER_COMMA = ',';
    public static final String DELIMITER_DOT = '.';
    public static final String DELIMITER_EQUAL = '=';
    public static final String DELIMITER_EXCLAMATION = '!';
    public static final String DELIMITER_HASH = '#';
    public static final String DELIMITER_SEMICOLON = ';';
    public static final String DELIMITER_SPACE = ' ';
    public static final String DELIMITER_UNDERSCORE = '_';
    public static final String DELIMITER_HYPHEN = '-';
    public static final String DELIMITER_AMPERSAND = '&';
    public static final String DELIMITER_QUESTION_MARK = '?';
    public static final String DELIMITER_BACKWARD_SLASH = '\'';
    public static final String DELIMITER_SINGLE_QUOTE = '\',';
    public static final String DELIMITER_FORWARD_SLASH = '/';
    public static final String DEFAULT_ONE = '-- Select One --';
    public static final String OPTION_NONE = '--None--';
    public static final String DELIMITER_PERCENTAGE = '%';
	public static final String BLANK_STRING = '';
    
   
    
}